name: Build OpenWrt Chip Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout chip-openwrt repository
      uses: actions/checkout@v4
      with:
        path: chip-openwrt

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj default-jdk flex bison gawk \
          gcc g++ libz-dev libssl-dev make perl python3.7+ subversion unzip \
          libncurses5-dev zlib1g-dev libelf-dev

    - name: Clone OpenWrt repository
      run: |
        git clone --single-branch --branch master --depth 1 \
          https://git.openwrt.org/openwrt/openwrt.git openwrt

    - name: Add custom feed for chip package
      run: |
        echo "src-git chip https://github.com/avaksru/chip-openwrt.git" >> openwrt/feeds.conf.default

    - name: Update and install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install chip

    - name: Create .config file
      run: |
        cd openwrt
        echo -e "CONFIG_TARGET_imx=y\nCONFIG_TARGET_imx_cortexa7=y\nCONFIG_TARGET_imx_cortexa7_DEVICE_geniatech_gtw360=y\nCONFIG_PACKAGE_cgi-io=y\nCONFIG_PACKAGE_liblucihttp=y\nCONFIG_PACKAGE_liblucihttp-ucode=y\nCONFIG_PACKAGE_luci=y\nCONFIG_PACKAGE_luci-app-firewall=y\nCONFIG_PACKAGE_luci-app-opkg=y\nCONFIG_PACKAGE_luci-base=y\nCONFIG_PACKAGE_luci-light=y\nCONFIG_PACKAGE_luci-mod-admin-full=y\nCONFIG_PACKAGE_luci-mod-network=y\nCONFIG_PACKAGE_luci-mod-status=y\nCONFIG_PACKAGE_luci-mod-system=y\nCONFIG_PACKAGE_luci-proto-ipv6=y\nCONFIG_PACKAGE_luci-proto-ppp=y\nCONFIG_PACKAGE_luci-theme-bootstrap=y\nCONFIG_PACKAGE_rpcd=y\nCONFIG_PACKAGE_rpcd-mod-file=y\nCONFIG_PACKAGE_rpcd-mod-iwinfo=y\nCONFIG_PACKAGE_rpcd-mod-luci=y\nCONFIG_PACKAGE_rpcd-mod-rrdns=y\nCONFIG_PACKAGE_rpcd-mod-ucode=y\nCONFIG_PACKAGE_ucode-mod-html=y\nCONFIG_PACKAGE_ucode-mod-math=y\nCONFIG_PACKAGE_uhttpd=y\nCONFIG_PACKAGE_uhttpd-mod-ubus=y\nCONFIG_ALL=n\nCONFIG_AUTOREMOVE=n\nCONFIG_AUTOREBUILD=n\nCONFIG_MBEDTLS_CCM_C=y\nCONFIG_PACKAGE_matter-netman-mbedtls=m\nCONFIG_PACKAGE_matter-netman-openssl=m\nCONFIG_PACKAGE_mdnsresponder=m\nCONFIG_PACKAGE_openthread-br=m\nCONFIG_PACKAGE_chip=m" > .config

    - name: Configure build
      run: |
        cd openwrt
        make defconfig

    - name: Build chip package
      run: |
        cd openwrt
        make -j$(nproc) package/chip/compile

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chip-package
        path: openwrt/bin/packages/*/*/chip*.ipk
