name: Build OpenWrt with Matter support

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  OPENWRT_VERSION: v24.10.0-20250212

jobs:
  build-openwrt:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache libelf-dev libncurses5-dev \
        libssl-dev python3 python3-dev unzip wget pkg-config libdbus-1-dev \
        libglib2.0-dev ninja-build git gcc g++ make
    
    - name: Download OpenWrt
      run: |
        wget https://github.com/openlumi/openwrt/archive/refs/tags/${{ env.OPENWRT_VERSION }}.tar.gz
        tar xvzf ${{ env.OPENWRT_VERSION }}.tar.gz
        mv openwrt-24.10.0-20250212 openwrt
    
    - name: Setup feeds and config
      run: |
        cd openwrt
        echo 'src-git chip https://github.com/avaksru/matter-openwrt.git' >> feeds.conf.default
        
        # Добавляем Matter конфигурацию
        if [ -f config_gtw360 ]; then
          echo -e "\n# Matter configuration" >> config_gtw360
          echo "CONFIG_PACKAGE_chip=y" >> config_gtw360
          echo "CONFIG_CHIP_TOOL=y" >> config_gtw360
          echo "CONFIG_CHIP_OTA_PROVIDER=y" >> config_gtw360
          echo "CONFIG_CHIP_BRIDGE=y" >> config_gtw360
        else
          cat > config_gtw360 << 'EOF'
CONFIG_PACKAGE_chip=y
CONFIG_CHIP_TOOL=y
CONFIG_CHIP_OTA_PROVIDER=y
CONFIG_CHIP_BRIDGE=y
EOF
        fi
        
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        cp config_gtw360 .config
        make defconfig
    
    - name: Build chip package
      run: |
        cd openwrt
        make -j$(nproc) package/chip/compile
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chip-packages
        path: openwrt/bin/packages/*/chip/*.ipk
