name: Build OpenWrt with Matter Host

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y \
            build-essential ccache ecj fastjar file g++ gawk \
            gettext git java-propose-classpath libelf-dev libncurses5-dev \
            libncursesw5-dev libssl-dev python3 python3-dev python3-setuptools \
            unzip wget rsync subversion gcc g++ pkg-config libdbus-1-dev \
            libglib2.0-dev ninja-build python3-venv swig time xsltproc zlib1g-dev \
            python-is-python3
          # Установка Python 2.7, если требуется
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install -y python2.7 python2.7-dev

      - name: Download and extract OpenWrt
        run: |
          wget https://github.com/openlumi/openwrt/archive/refs/tags/v24.10.0-20250212.tar.gz
          tar xvzf v24.10.0-20250212.tar.gz
          mv openwrt-24.10.0-20250212 openwrt
          cd openwrt
          pwd  # Вывод текущей директории для отладки

      - name: Configure OpenWrt for Matter Host
        run: |
          cd openwrt
          cat << EOF > config_gtw360
          CONFIG_PACKAGE_chip=y

          #
          # Configuration for Matter Host
          #
          CONFIG_CHIP_TOOL=y
          CONFIG_CHIP_OTA_PROVIDER=y
          CONFIG_CHIP_BRIDGE=y
          # end of Configuration for Matter Host
          EOF
          cp config_gtw360 .config
          make -j$(nproc) defconfig

      - name: Add custom feed
        run: |
          cd openwrt
          echo "src-git chip https://github.com/avaksru/chip-openwrt.git" >> feeds.conf.default
          cat feeds.conf.default  # Вывод конфигурации feeds для отладки

      - name: Update and install feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a || { echo "Ошибка обновления feeds"; exit 1; }
          ls -la feeds/  # Вывод содержимого директории feeds для отладки
          if [ ! -d "feeds/chip" ]; then
            echo "Ошибка: директория feeds/chip не найдена"
            exit 1
          fi
          ./scripts/feeds install -a || { echo "Ошибка установки feeds"; exit 1; }

      - name: Compile chip package
        run: |
          cd openwrt
          make -j$(nproc) package/chip/compile V=s || { echo "Ошибка компиляции пакета chip"; exit 1; }

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-chip-package
          path: openwrt/bin/packages/*/*/chip/*.ipk
